# Generated by Django 3.1.5 on 2021-01-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='when',
            field=models.CharField(default=0.0, max_length=300),
            preserve_default=False,
        ),
    ]
